# configs/trainer/oa2022.yaml
_target_: gunflows.trainer.OA2022Trainer

epochs: 20000
batch_size: 10000
num_val: 3000
val_every: 100
device: cuda
seed: 42            # trainer-local seed (used to split train/val)

early_stop:
  patience: 10
  min_delta: 100
  min_epoch: 20000

loss:
  name_train: exp_symmetric
  name_val:   exp_symmetric
  cap: .inf
  kwargs:
    a: 1.0
    b: 1.0
