_target_: gunflows.flows.systematic_flow
total_dim: 711
dim_spline: ${len:${experiment.dataset.phase_space_dim}}

# RQ-NSF
nflows: 25
hidden: 256
nlayers: 1
nbins: 21
tail_bound: 7.0

# Cov Flow
freeze_covflow: false

# Context Flow
context_transform: true
n_context_flows: 12
n_hidden_layers: 2
hidden_dim: 512
