_target_: gunflows.flows.systematic_flow
total_dim: 711
dim_spline: ${len:${experiment.dataset.phase_space_dim}}

# RQ-NSF
nflows: 10
hidden: 512
nlayers: 1
nbins: 11
tail_bound: 3.0

# Cov Flow
freeze_covflow: true

# Context Flow
context_transform: true
n_context_flows: 12
n_hidden_layers: 2
hidden_dim: 64
