_target_: gunflows.dataset.systematic_dataset_oa2022.SystematicDatasetOA2022

phase_space_dim: 
    [100,101,102,103,104,105,106,107,108,109]

  # starting_folder is where the initial samples are saved
starting_folder: /workspace/config/GundamWorkspace/datasets_sb_configToyOANoMirrorFakeData_100plus10
with_sampler: true
nf_ckpt: null                     # path to NF checkpoint if available
data_dir: ${hydra:runtime.output_dir}/generated_samples
gen_batch_size: 50000
max_batches: 50
num_samplers: 10

llh_config: /workspace/config/GundamWorkspace/output/gundamFitter_configToyOANoMirrorFakeData_100plus10.root
llh_overrides: []
llh_cwd: /workspace/config/GundamWorkspace

seed: 42
queue_size: 1000
timeout: 60000000.0
plot_grid: true
out_dir: ${hydra:runtime.output_dir}/plots
data_is_asimov: false
