_target_: gunflows.dataset.systematic_dataset_oa2022.SystematicDatasetOA2022

phase_space_dim:
  [60,61,62,63,64,65]

starting_folder: /workspace/config/GundamWorkspace/datasets_asimovfit_toyOA_60plus6_seed_6
# batch_index: null

with_sampler: true
nf_ckpt: null
data_dir: ${hydra:runtime.output_dir}/generated_samples
gen_batch_size: 10000
max_batches: 100
num_samplers: 10

llh_config: /workspace/config/GundamWorkspace/outputs/asimovfit_toyOA_60plus6_seed_6.root
llh_overrides: []
llh_cwd: /workspace/config/GundamWorkspace
data_is_asimov: False

seed: 42
queue_size: 1000
timeout: 60000000.0
plot_grid: true
out_dir: ${hydra:runtime.output_dir}/plots

# load_data: true


