_target_: gunflows.dataset.systematic_dataset_oa2022.SystematicDatasetOA2022

phase_space_dim:
  [100,101,102,103,104,105,106,107,108,109]

starting_folder: /workspace/config/GundamWorkspace/datasets_gundamFitter_configToyOA_100plus10_Asimov_2
# batch_index: null

with_sampler: true
nf_ckpt: null
data_dir: ${hydra:runtime.output_dir}/generated_samples
gen_batch_size: 10000
max_batches: 200
num_samplers: 10

llh_config: /workspace/config/GundamWorkspace/output/gundamFitter_configToyOA_100plus10_Asimov.root
llh_overrides: []
llh_cwd: /workspace/config/GundamWorkspace
data_is_asimov: True

seed: 42
queue_size: 1000
timeout: 60000000.0
plot_grid: true
out_dir: ${hydra:runtime.output_dir}/plots

# load_data: true


