defaults:
  - override hydra/job_logging: disabled
  - _self_

likelihood:
  config: /workspace/config/GundamInputOA2021/output/gundamFitter_configOa2021_With_allowEigenDecompWithBounds_Asimov.root
  overrides: []
  cwd: /workspace/config/GundamInputOA2021
  threads: 6
  asimov: true

seed: 42
n_steps: 20000
burn_in: 1000  # discard this many initial steps
proposal_scale: 0.01
initial_point: null # if null, use the postfit best fit point
out_file: chain.npz
save_dir: null

plot:
  dims: [652, 653, 654, 655, 656, 657, 658, 659, 660,
                  661, 662, 663, 664, 665, 666, 667, 668, 669]
  every: 10000

